### PR TITLE
Support for new cluster and streams commands.

### PR DESCRIPTION
**Pull request by kak-tus**
- COMMAND (partly, only full command list);
- CLUSTER SLOTS. For go-redis/redis cluster connection;
- XGROUP CREATE;
- XINFO STREAM (partly, only stream length);
- XREADGROUP (partly, BLOCK and NOACK arguments not processed);
- XACK;
- XDEL.

### CODE REVIEW

**Comment by kak-tus** [comment]
Some commands realized partly - only for add tests with miniredis to my project Ami.

**Comment by alicebob** [comment]
Hi @kak-tus , thanks for the PR!
It looks very interesting, I'll have a good look soon.

**Comment by alicebob** [comment]
It looks all good. Would it be possible to add some tests to ./integration/ ?

**Comment by kak-tus** [comment]
How to do better of results comparison for "XINFO STREAM"?
In miniredis it realized partly because of "radix-tree-keys" and "radix-tree-nodes" internal redis values "details about the radix tree representing the stream mostly useful for optimization and debugging tasks".
My opinion - to add succPartly (or succListPartly) function, than compares only that part of result, that user set.

**Comment by alicebob** [comment]
> How to do better of results comparison for "XINFO STREAM"?
> In miniredis it realized partly because of "radix-tree-keys" and "radix-tree-nodes" internal redis values "details about the radix tree representing the stream mostly useful for optimization and debugging tasks".
> My opinion - to add succPartly (or succListPartly) function, than compares only that part of result, that user set.

Maybe it's already enough if we only compare the basics:
- `XINFO STREAM` should return no error in both
- `XINFO STREAMMM` should error in both
- `XINFO STREAM foo` should error in both
- `XINFO` should error in both

I don't think testing the exact responses is worth the time investment, given
how they change.

**Comment by kak-tus** [comment]
Ready.

**Comment by alicebob** [comment]
Thanks! I'll have a look in a few days.

The build did fail, did you forget to add a file?

**Comment by kak-tus** [comment]
Yes, I forget to add "+build int" header to new files.

**Comment by alicebob** [comment]
Thanks! I merged this to master, I'll make a new release in a few days.

**Pull request closed without merging**
