### PR TITLE
Support XAUTOCLAIM

### PR DESCRIPTION
**Pull request by randall-fulton**
Add support for XAUTOCLAIM, to address #254.

### CODE REVIEW

**Comment by alicebob** [comment]
Thanks for the PR! I'll have a better look later, but would it be possible to add some tests to the /int/ dir? Might be tricky with xautoclaim, though.

**Comment by randall-fulton** [comment]
No problem. I've used this package in the majority of projects over the past few years. I'm due a bit of contribution.

I'll give it a shot.

**Comment by randall-fulton** [comment]
@alicebob I missed updating the unit tests after fixing a bug the integration tests found. My mistake for not running them before I pushed.

**Comment by alicebob** [comment]
Hi, thanks for the fixes. I had a look, and as I understand the command it should do the actual claiming as well, so I updates the code. Does that make sense to you?

**Comment by randall-fulton** [comment]
@alicebob looks good to me. Appreciate the help polishing it off.

**Comment by alicebob** [comment]
On Mon, May 02, 2022 at 05:42:11AM -0700, Randall Fulton wrote:
> @alicebob looks good to me. Appreciate the help polishing it off.

Great, thank for checking! If you can squash the commits that would be great
(otherwise you won't get credit for it).

**Pull request merged**
