### PR TITLE
Precompile lua functions to prevent wasted CPU cycles

### PR DESCRIPTION
**Pull request by tonyhb**
`miniredis.runLuaScript` calls lua.*LState.DoString() for every lua invocation, even if scripts are evaluated via checksums.

In turn, lua parses and compiles the same scripts on each call, which can cause high CPU usage on script-heavy test instances.

This PR uses `sync.Map` to store pre-compiled lua functions for each script, using the same logic as the Lua library itself: https://github.com/tul/gopher-lua/commit/7a6135d85e95b76c9f304a56804402c829273f0f

This reduces CPU usage by about 50%.

Before:

Screenshot 2023-05-16 at 18 24 25

After:

Screenshot 2023-05-16 at 18 28 09

This takes `runLuaScript`'s cumulative time from 1.19s to 0.68s, or about a 57% improvement.

### CODE REVIEW

**Comment by alicebob** [comment]
Hi,

thanks for the clear PR! It looks good, but some error messages changed. The errors can't have the exact same wording as Redis, but they should use the same `-ERR ..` prefix. Nothing major, if you could have a look at that, great, otherwise I have a better look another time.

**Comment by tonyhb** [comment]
@alicebob thanks for the quick review!  believe that i've fixed that error, appreciate the heads up :)

**Comment by alicebob** [comment]
Hi,

thanks for the fix. Just the test failure left. I see the Lua code eventually does this in `DoString()`:

> 	return ls.Load(strings.NewReader(source), "<string>")

https://github.com/yuin/gopher-lua/blob/v1.1.0/auxlib.go#L387

so maybe do it that way?

**Comment by alicebob** [comment]
Thanks! It's now in master.

**Pull request merged**
