### PR TITLE
Implement PUB/SUB

### LINKED ISSUE #1: PubSub Implementation
Do you have any intention on implementing the Pubsub portion of Redis?

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #1

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Hello again @alicebob!

To be honest I've not even read all my changes together in a chilly minute – so I can't even tell whether that stuff will work.

However feel free to scroll through and complain about my architecture (if there's anything to complain about).

Will test that tomorrow.

Best,
AK

**Comment by Al2Klimov** [comment]
@alicebob Now it runs like a bunny – and I'll continue with the "backend PUB/SUB". Once you give green light for the stuff added so far, I'll write docs + tests.

**Comment by Al2Klimov** [comment]
PS: You Travis seems to be broken and it was also in #50. Please could you have a look?

**Comment by Al2Klimov** [comment]
Direct stuff – done.

**Comment by alicebob** [comment]
Hi @Al2Klimov 
thanks again for the PR. I just went over the code and most of it made sense. I do have some bigger-picture questions which I'm curious about. I'm not 100% familiar with the redis pub/sub behavior, so it might well be there are reasons for something which I don't understand.

- The server now has support for writing messages. Would it be possible to keep that logic out of the server?
- I think you can use channels in maps directly (either as keys or as values) more often. I think it would simplify some code since you won't need to use slices as buffers.
It feels to me that a subscription shouldn't need to be more than essentially a `chan string`, with a simple go-routine which writes everything sent the the channel to the client.

I suggest to add unittests to show things work as advertised, and then we can move on.

thanks!

**Comment by Al2Klimov** [comment]
Hi @alicebob

1. I'm afraid no. A PUBLISHed message is not a direct result of a `{,P}SUBSCRIBE` so it would be wrong to wait while handling `{,P}SUBSCRIBE`. It also would block additional `{,P}{,UN}SUBSCRIBE`s and PINGs.
2. I wanted to do so, but then I discovered that Go doesn't support infinite-size channels. That's why I used queues. Sure, I could do it with goroutines as well, but this would add complexity – especially in cleaning up subscribers and peers.

Best,
AK

**Comment by alicebob** [comment]
morning :)

1.: could you keep a goroutine around which writes to the client when there is something to write?
2.: why do you need infinite-size channels? If a socket is filling up that means something is wrong and you can close it. That would be a channel with a small buffer, and a reader as in the point above.

But again, I'm not 100% familiar with the pubsub behaviour.

**Comment by Al2Klimov** [comment]
1. ... causing to mix up contents of sync and async responses? No, thanks.
2. If a client disconnects while an undefined number of async messages appears... difficult.

Anyway... IMO these are just implementation details and the current implementation works. Time for tests...

**Comment by Al2Klimov** [comment]
Will continue on monday.

**Comment by Al2Klimov** [comment]
Have I already told you... that [the Travis situation is weird](https://travis-ci.org/Al2Klimov/miniredis/builds/426561453)?

**Comment by Al2Klimov** [comment]
Now all new commands are tested one-by-one.
Will chain everything together tomorrow.

@alicebob Please explain what exactly `integration/` is for. On the first sight it seems to run an actual Redis, but... aren't we kinda substituting Redis?

**Comment by alicebob** [comment]
@Al2Klimov : integration indeed runs an actual redis. I sends a sequence of commands to both a real and a miniredis, and compares that the output is the same. Very useful to run on new releases of Redis.

**Comment by Al2Klimov** [comment]
So I'll just "copy&paste" my unit test cases to `integration/` once done?

**Comment by alicebob** [comment]
I would take a representative subset. I think writing those test for pub/sub will be a bit trickier to do than for the normal commands, since it's more in parallel, but it would still be nice to have a few. It's also to have some tests for the error messages, so you can show they are the same.

I'll be offline for a week, so I won't be able to review this PR the next few days. On the plus side you have more time to test it :)

**Comment by Al2Klimov** [comment]
Just discovered a bug (?) in [cmd_list_test.go:15](https://github.com/alicebob/miniredis/blob/a6a1e4126522b7574194e7c6914457f431285cb7/cmd_list_test.go#L15): You seem not to close `c1`.

Does this work as intended?

**Comment by Al2Klimov** [comment]
TODO:

* [ ] test direct stuff
* [ ] integrations

**Comment by Al2Klimov** [comment]
I'm afraid I'll have to do a break in this, but I'll definitely come back.

**Comment by Al2Klimov** [comment]
Hello again @alicebob!

Now it's your turn.

**Comment by alicebob** [comment]
On Fri, Nov 16, 2018 at 01:54:03AM -0800, Alexander Aleksandrovič Klimov wrote:
> Hello again @alicebob!
> 
> Now it's your turn.

You're done? Thanks! I'll have a proper look when I have some time.

**Comment by Asalle** [comment]
@alicebob ping

**Comment by Asalle** [comment]
I tried to build this pr locally and got the error:
```
make -k 
go test ./...
# _/home/asalle/work/foss/miniredis
./direct.go:967:6: error: reference to undefined field or method ‘MsgQueue’
  peer.MsgQueue.Enqueue(&queuedPubSubMessage{channel, message})
      ^
./miniredis.go:169:3: error: reference to undefined field or method ‘OnDisconnect’
  s.OnDisconnect(m.onDisconnect)
   ^
FAIL	_/home/asalle/work/foss/miniredis [build failed]
ok  	_/home/asalle/work/foss/miniredis/server	(cached)
make: *** [Makefile:9: test] Error 2

```
my travis build showed the [same](https://travis-ci.org/Asalle/miniredis/builds/501572313).

Am I doing something wrong?

**Comment by alicebob** [comment]
Hi! Sorry for the delays.

I just merged this PR, with some changes. Most notably that subscriptions are not related to the `SELECT`ed database, but it's a separate system. But it all seems to work now. Thanks for the PR!

**Comment by Al2Klimov** [comment]
@Crunsher @N-o-X Happy unit testing.

**Pull request closed without merging**
