### PR TITLE
feat: Add zpopmax and zpopmin

### PR DESCRIPTION
**Pull request by joeirimpan**
credits to https://github.com/alicebob/miniredis/pull/63

* added integration test
* fixed zpopmax, zpopmin

### CODE REVIEW

**Comment by alicebob** [comment]
Thanks! I looks good, but I'll have a proper look and poke it a bit in a few days.

**Comment by joeirimpan** [comment]
cool

**Comment by joeirimpan** [comment]
@alicebob Just reminding if you missed this out.

**Comment by alicebob** [comment]
Hi, sorry, wanted to get the pubsub PR through first.

Thanks for the commit! I merged it just now.

**Pull request merged**
