### PR TITLE
Added SWAPDB command

### PR DESCRIPTION
**Pull request by linuxfreak003**
Added SWAPDB command. Some whitespace changed crept in there too (my editor automatically truncates trailing whitespace)

### CODE REVIEW

**Comment by alicebob** [comment]
Hi! Thanks for the PR. Looks good after a quick read. Could you add a basic test in `./integration/` for it, as well?

**Comment by linuxfreak003** [comment]
I added a test in `./integration/`. Though I must confess I'm not incredibly familiar with the code there. I didn't take a long look just tried to add the test the best I could surmise.

**Comment by alicebob** [comment]
> I added a test in `./integration/`. Though I must confess I'm not incredibly familiar with the code there. I didn't take a long look just tried to add the test the best I could surmise.

Thanks!
I'll have a look in a few days. It all looks pretry straightforward :)

**Comment by alicebob** [comment]
Thanks, merged and released as v2.7.0!

https://github.com/alicebob/miniredis/releases/tag/v2.7.0

**Pull request closed without merging**
