### PR TITLE
Implementing Count functionality in SSCAN

### PR DESCRIPTION
**Pull request by Abdi-dd**
Currently miniredis does not utilize the [count functionality ](https://redis.io/commands/scan/), defaulting any use to 0. 

This change utilizes the use of adding in the functionality to support count in SSCAN and also allowing the use of a cursor arg to be passed in as well. 

[Link to an issue:](https://github.com/alicebob/miniredis/issues/147)

### CODE REVIEW

**Comment by alicebob** [comment]
thanks for the PR! I'll have a look soon (vacation)

**Comment by alicebob** [comment]
Thanks!

**Comment by Abdi-dd** [comment]
Thank you for merging this ticket!

I wanted to go ahead and start using this functionality, can I get an update on when you plan on releasing a new version with these changes?

**Comment by alicebob** [comment]
> I wanted to go ahead and start using this functionality, can I get an update on when you plan on releasing a new version with these changes?

Ah yeah, just made v2.23.0. Thanks!

**Pull request merged**
