### PR TITLE
Fix race condition in blocking()

### PR DESCRIPTION
**Pull request by zonque**
Currently there is a race condition in `blocking()`.

The code is waiting for the `m.signal` condition to fire in a goroutine, and that routine is supposed to be stopped in case of timeouts or context termination with an extra `Broadcast()` call.

When the global server context is already done upon entering that function however, the broadcast will race against the scheduling of the goroutine, and in case it misses its target, the waitgroup operation will never finish and the process deadlocks.

To fix this, turn the logic on its head and wait for the condition synchronously, and send a signal from a goroutine in case we hit a timeout or the context is terminated.

This isn't an artificial case. The bug can be reproduced with go-redis/v8 and the following snippet:

```go
package main

import (
	"context"
	"fmt"
	"sync"

	"github.com/alicebob/miniredis/v2"
	"github.com/go-redis/redis/v8"
)

func main() {
	mini, err := miniredis.Run()
	if err != nil {
		panic(err)
	}

	redis := redis.NewUniversalClient(&redis.UniversalOptions{
		Addrs: []string{mini.Addr()},
	})

	ctx, cancel := context.WithCancel(redis.Context())

	redis.LPush(ctx, "x", "a")

	var wg sync.WaitGroup
	wg.Add(1)

	go func() {
		for {
			_, err := redis.BRPop(ctx, 0, "x").Result()
			if err == nil {
				wg.Done()
			}
		}
	}()

	fmt.Printf("Waiting ...\n")
	wg.Wait()

	fmt.Printf("Cancelling ...\n")
	cancel()
	redis.Close()
	mini.Close()

	fmt.Printf("Done.\n")
}

```

### CODE REVIEW

**Comment by zonque** [comment]
Note that this patch doesn't properly fix the issue either, it just makes it a whole lot less likely to trigger, and my tests corroborate that. The real fix would require the condition logic to be replaced by something `select{}`able, as `sync.Cond` and timeouts don't play nicely together.

**Comment by alicebob** [comment]
On Thu, Sep 02, 2021 at 01:24:21PM -0700, Daniel Mack wrote:
> Currently there is a race condition in `blocking()`.

Thanks for the issue and PR! I'll have a look soonish.

**Comment by alicebob** [comment]
Also, say hello to Christian ;)

**Comment by danrex** [comment]
He did 😜

**Comment by zonque** [comment]
I added a patch now that should close the race gap that still persisted. Albeit not pretty it should fully fix the issue now.

**Comment by alicebob** [comment]
Hi @zonque. Thanks again for the issue and the fix. I went with the solution from #223, which fixes the problem and also makes the general logic a bit cleaner.

**Comment by zonque** [comment]
Nice! Added some comments there.

Closing this one, nice to see this issue solved!

**Pull request closed without merging**
