### PR TITLE
just an idea of where I'm headed with this PR - not intended for a merge, just some more discussion

### PR DESCRIPTION
**Pull request by Jim-Lambert-Bose**

### CODE REVIEW

**Comment by alicebob** [comment]
Thanks!

Seems to make sense, after reading through.

I would prefer if it could be implemented without adding any new dependencies (at least for non-test code). The `uuid` one could be avoided by generating some stable uuid, which is likely nice for testing anyway. The `deepcopy` one I don't know.

**Comment by alicebob** [comment]
As a side thought: you can also publish it under your own name. I would be happy to link to it in the README.md

**Comment by Jim-Lambert-Bose** [comment]
Hum... happy to just publish it in a separate repo.  But, it might take a month or so to get Bose sign-off on the OSS contribution in a separate repo.  Is it okay to wait that long?  If not, we can just add it to your repo.  Up to you which way you'd prefer to go.

**Comment by Jim-Lambert-Bose** [comment]
Okay, looks like I'll get approval for this OSS contribution so I'll release it myself in a separate repo.  Ty for your feedback.  I'll ping you in a week or so when it's all set up and you can link to it.

**Pull request closed without merging**
