### PR TITLE
Implement LMOVE

### PR DESCRIPTION
**Pull request by btwear**
Hi, I found there is no LMOVE command currently, so I implement it with tests.
Most of my works are based on RPOPLPUSH implementation.

### CODE REVIEW

**Comment by alicebob** [comment]
On Wed, Jan 12, 2022 at 07:16:29PM -0800, btwear wrote:
> LMOVE command implementation with tests. Most of work is based on RPOPLPUSH.
> You can view, comment on, or merge this pull request online at:

Thanks! I'll have a look soon. Could you add some simple tests to the relevant test in ./integration/ as well?

**Comment by btwear** [comment]
@alicebob 
Sure, I just pushed a amend commit with integration test.

**Comment by alicebob** [comment]
What a funny redis command. PR looks good when doing a basic read over it, will have a proper look soon.

**Comment by alicebob** [comment]
great PR, thanks!

Merged in master, will make it a release it later today.

**Pull request merged**
