### PR TITLE
implement Copy command

### PR DESCRIPTION
**Pull request by matiasinsaurralde**
First attempt at implementing `Copy` command (#241), still need to polish some stuff

### CODE REVIEW

**Comment by alicebob** [comment]
Hi,

thanks!, looks good in general. You'll also want to add some tests to `./integration/generic_test.go`, which will likely help you to get the error cases correctly.

**Comment by matiasinsaurralde** [comment]
> Hi,
> 
> thanks!, looks good in general. You'll also want to add some tests to `./integration/generic_test.go`, which will likely help you to get the error cases correctly.

Great, I will look into that during the week.

Thanks for the feedback.

**Comment by matiasinsaurralde** [comment]
@alicebob I've added initial test cases which should cover the most basic functionality of the `copy` command.

I believe that a separate PR could be prepared for supporting the two optional arguments (`db` and `replace`), as described [here](https://redis.io/commands/copy).

Test output:
```
% go test . -v -tags 'int' -run Copy
=== RUN   TestCopy
--- PASS: TestCopy (0.02s)
PASS
ok  	github.com/alicebob/miniredis/v2/integration	(cached)
% redis-cli info | grep redis_version
redis_version:6.2.6
```

**Comment by alicebob** [comment]
thanks! I'll have a look soon.

**Comment by alicebob** [comment]
ah, I forgot, can you squash the commits? That's easier for me to merge them later. Thanks!

**Comment by matiasinsaurralde** [comment]
@alicebob Squashed 👍

**Comment by rockitbaby** [comment]
Thank you for contributing @matiasinsaurralde – this looks good to me!
Minor: Do not forget to add COPY to the list of implemented commands in README.md

**Comment by matiasinsaurralde** [comment]
@rockitbaby Thanks for the suggestion, have updated the README

**Comment by alicebob** [comment]
Hi! thanks for the last fix. I was just finishing this. I've added support for `DB` and `REPLACE` in #244. But the `DB` argument wouldn't work with the existing implementation, so I've changed the `m.Copy()` to be `m.Copy(0, "from", 0, "to")` (or whichever database IDs you want).
There was a serious bug that you didn't copy the contents of keys (such as hashes), which means that changing the old key would also change the copy. That's also fixed.

**Comment by matiasinsaurralde** [comment]
@alicebob Thanks, looking good

**Comment by alicebob** [comment]
thanks! it's merged in master

**Pull request closed without merging**
