### PR TITLE
Add HEXPIRE support

### PR DESCRIPTION
**Pull request by Daniel-W-Innes**
Add the [HEXPIRE](https://redis.io/docs/latest/commands/hexpire/) command by tracking ttls for each field in hashTtls.

### CODE REVIEW

**Comment by alicebob** [comment]
On Tue, Oct 08, 2024 at 09:09:03AM -0700, Daniel Innes wrote:
> Add the [HEXPIRE](https://redis.io/docs/latest/commands/hexpire/) command by tracking ttls for each field in hashTtls.

Thanks for the PR!, I'll have a look soon. It will need some tests under
./integration/, which I'm happy to add if it's unclear how they work.

**Comment by alicebob** [comment]
hi @Daniel-W-Innes , any reason you closed this?

**Comment by Daniel-W-Innes** [comment]
> hi @Daniel-W-Innes , any reason you closed this?

Yes, HEXPIRE is from 7.4.0, and I noticed while creating the integration test that it is after the 7.2.6 cut-off for this project.

**Comment by Daniel-W-Innes** [comment]
I reopened this because I think we can still add the feature, but I'm not sure how you would like me to handle the integration tests.

**Comment by alicebob** [comment]
Thanks for the explanation, I'll get back to you later. Hasn't happened yet that there were features added from after the license change.

(the PR itself looks nice and clear)

**Comment by alicebob** [comment]
Hi @Daniel-W-Innes, thanks again for your PR.

I will stick to testing against the last open version of Redis, and that means I can't add things I can't test (if only because it's unmaintainable). If one day a Redis fork shows up I'll keep this PR in mind.

**Pull request closed without merging**
