### PR TITLE
Tests: reduce volatility

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Why? See the latest Travis build.

I'd like this to be merged before #49 (so I can rebase #49).

**Comment by alicebob** [comment]
I'll try it with #54 first. It expect it's some timing related issue with shutting down the socket, but now it's avoided.

**Comment by Al2Klimov** [comment]
I'd still prefer this one as

1. 2x QUIT should be tested, too
2. IMAO it's enough when the integration succeed 1 of 4 times

**Comment by alicebob** [comment]
the 2xQuit used to work on Travis. I guess they changed something.

I really prefer to fix the problem, and have stable tests. Hiding problems by running tests multiple times doesn't sound good to me.

**Comment by alicebob** [comment]
I'll keep the simpler version.

**Comment by Al2Klimov** [comment]
@Crunsher @N-o-X Happy unit testing.

**Pull request closed without merging**
